[package]
name = "pyo3-generic-wrap"
version = "0.1.0"
authors = ["Maximilian KÃ¶hl <koehl@cs.uni-saarland.de>"]
edition = "2018"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "^1.0"
syn = { version = "^1.0", features = ["full"] }
quote = { version = "^1.0" }
